# Generated by Django 5.0.6 on 2024-07-27 06:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaved_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('person_age', models.CharField(max_length=255)),
                ('added_date', models.DateField(default=None)),
                ('leave_date', models.DateField(default=django.utils.timezone.now)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostels.beds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostels.members')),
            ],
        ),
    ]
