# Generated by Django 5.0.6 on 2024-07-27 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0002_leaved_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beds',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
