# Generated by Django 5.0.6 on 2024-08-30 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0003_alter_beds_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_id', models.CharField(default=None, max_length=255)),
                ('person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('in_out_status', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostels.members')),
            ],
        ),
    ]
