# Generated by Django 5.0.6 on 2024-08-30 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0004_in_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_out',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
